"""
Week 1 本編動画のシーン別ビジュアルデータ。
"""

SCENE_VISUAL: dict[str, dict] = {
    "O1": {"type": "welcome", "title": "ようこそ。", "subtitle": "Week 1 — はじめての Claude Code"},
    "O2": {"type": "promise", "pretext": "30 分後、あなたの PC で。", "main": "本物のアプリが、", "main_accent": "動いている", "post": "コードは、1 行も書かない。"},
    "1-1": {"type": "chapter", "num": "1", "title": "Claude Code って、何?"},
    "1-2": {
        "type": "comparison",
        "left_label": "普通の AI",
        "left_text": "「メモ帳の作り方を教えて」\n→ 文字で説明してくれる",
        "left_role": "知識豊富な相談相手",
        "right_label": "Claude Code",
        "right_text": "「メモ帳を作って」\n→ 本当にアプリを作る",
        "right_role": "手を動かす部下",
        "highlight": "right",
    },
    "1-3": {
        "type": "statement",
        "main": "クロード・コードは、",
        "main_accent": "実際に手を動かす",
        "sub": "文章で答えるのではなく、PC の中でファイルを作り、コードを書き、アプリを動かす。",
    },
    "1-4": {
        "type": "duo",
        "left_label": "普通の AI",
        "left_role": "= 相談相手",
        "right_label": "Claude Code",
        "right_role": "= 部下",
    },
    "1-5": {
        "type": "iconography",
        "header": "日本語で頼むだけで、何が作れる?",
        "items": [
            {"icon": "📱", "label": "アプリ"},
            {"icon": "🌐", "label": "Web サイト"},
            {"icon": "🤖", "label": "AI 機能"},
            {"icon": "💳", "label": "決済機能"},
        ],
    },
    "1-6": {"type": "statement", "main": "Claude Code = ", "main_accent": "あなたの優秀な部下", "sub": "日本語で頼むと、本当に動いてくれる。"},
    "2-1": {"type": "chapter", "num": "2", "title": "なぜ、今がチャンスなのか"},
    "2-2": {
        "type": "comparison",
        "left_label": "10 年前",
        "left_text": "・プログラミング言語を\n  数年学習\n・外注で数百万円",
        "left_role": "ハードルが高すぎた",
        "right_label": "今",
        "right_text": "・日本語で頼むだけ\n・30 分で完成\n・誰でも作れる",
        "right_role": "革命が起きた",
        "highlight": "right",
    },
    "2-3": {"type": "big_statement", "main": "革命", "sub": "日本語 ・ 30 分 ・ 無料 ・ 誰でも"},
    "2-4": {"type": "stats", "big": "99 %", "label": "の人は、まだ気づいていない。", "footer": "気づいた人から、圧倒的な差がつく。"},
    "3-1": {"type": "chapter", "num": "3", "title": "PC にインストールしよう"},
    "3-2": {"type": "terminal", "label": "Mac の方", "lines": ["1. ⌘ + Space", "2. 「ターミナル」と打つ", "3. Enter"], "footer": "黒い画面が開いたら成功"},
    "3-3": {"type": "terminal", "label": "Windows の方", "lines": ["1. Windows キー", "2. 「PowerShell」と打つ", "3. Enter"], "footer": "青い画面が開いたら成功"},
    "3-3b": {"type": "terminal_cmd", "label": "インストールコマンド", "command": "npm install -g @anthropic-ai/claude-code", "footer": "コピー & ペースト → Enter"},
    "3-4": {"type": "terminal_cmd", "label": "起動", "command": "claude\n>", "footer": "矢印 (>) が出たら成功 ✨"},
    "3-5": {"type": "checklist", "header": "うまくいかなかったら", "items": ["ターミナルを再起動", "コミュニティに投稿", "30 分以内に必ず解決"], "footer": "1 人で抱え込まない、これが鉄則"},
    "4-1": {"type": "chapter", "num": "4", "title": "最初の一言を、話しかけてみよう"},
    "4-2": {"type": "terminal_cmd", "label": "最初の挨拶", "command": "> こんにちは\n\n✓ こんにちは!\n  お手伝いできることはありますか?", "footer": "AI が返事をくれた = 接続成功"},
    "4-3": {"type": "terminal_cmd", "label": "ファイルを作ってもらう", "command": "> このフォルダに hello.txt を作って\n\n✓ 作成: hello.txt", "footer": "本当にファイルが PC の中に生まれる"},
    "4-4": {"type": "big_statement", "main": "動いた。", "sub": "あなたの世界は、今、変わり始めた。"},
    "5-1": {"type": "chapter", "num": "5", "title": "メモ帳アプリを、作ってもらおう"},
    "5-2": {"type": "terminal_cmd", "label": "フォルダ移動 + 起動", "command": "$ cd ~/my-apps\n$ claude\n>", "footer": "作業フォルダに入って、Claude Code 起動"},
    "5-3": {"type": "terminal_cmd", "label": "一言で完成", "command": "> シンプルなメモ帳アプリを作って。\n  白い背景で、文字が自動保存されるやつ。\n\n✓ index.html\n✓ style.css\n✓ app.js", "footer": "Claude Code が必要なファイルを自動生成"},
    "5-4": {"type": "statement", "main": "ダブルクリック → ", "main_accent": "ブラウザで動く", "sub": "文字を打って、閉じて、もう一度開いても、書いた内容が残っている。"},
    "5-5": {"type": "big_statement", "main": "あなたは、作れる人になった。", "sub": "おめでとう。"},
    "6-1": {"type": "chapter", "num": "6", "title": "上手に頼む 5 つのコツ"},
    "6-2": {"type": "tip", "num": "1", "tip": "具体的に", "bad": "「メモ帳作って」", "good": "「白背景、文字保存つきメモ帳」"},
    "6-3": {"type": "tip", "num": "2", "tip": "一度に 1 つだけ", "bad": "5 個同時にお願い", "good": "1 個ずつ完成 → 次へ"},
    "6-4": {"type": "tip", "num": "3", "tip": "例を見せる", "bad": "「いい感じに」", "good": "「Notion みたいに」"},
    "6-5": {"type": "tip", "num": "4", "tip": "ここを → こうして", "bad": "「なんか違う」", "good": "「タイトル色を黒に」"},
    "6-6": {"type": "tip", "num": "5", "tip": "褒めてから直す", "bad": "「ダメ、直して」", "good": "「最高!1 点だけ…」"},
    "7-1": {"type": "checklist", "header": "今週の宿題", "items": ["好きなアプリを 3 つ作る", "スクリーンショットを撮る", "コミュニティに投稿"], "footer": "電卓・占い・ゲーム、何でも OK"},
    "7-2": {"type": "closing", "main": "Week 2 で、", "main_accent": "また会いましょう", "sub": "あなたは、もう作れる人です。"},
}
